# CMake generated Testfile for 
# Source directory: /Users/seanashton/src/dcmtk-ios/dcmtk/dcmsr/tests
# Build directory: /Users/seanashton/src/dcmtk-ios/xcode/dcmsr/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(dcmsr_addTreeNode_1 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_addTreeNode_1")
set_tests_properties(dcmsr_addTreeNode_1 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_addTreeNode_2 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_addTreeNode_2")
set_tests_properties(dcmsr_addTreeNode_2 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_addTreeNode_3 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_addTreeNode_3")
set_tests_properties(dcmsr_addTreeNode_3 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_getPosition "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_getPosition")
set_tests_properties(dcmsr_getPosition PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_countChildNodes "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_countChildNodes")
set_tests_properties(dcmsr_countChildNodes PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_treeWithoutRoot "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_treeWithoutRoot")
set_tests_properties(dcmsr_treeWithoutRoot PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_copyTree "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_copyTree")
set_tests_properties(dcmsr_copyTree PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_assignTree "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_assignTree")
set_tests_properties(dcmsr_assignTree PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_cloneSubTree_1 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_cloneSubTree_1")
set_tests_properties(dcmsr_cloneSubTree_1 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_cloneSubTree_2 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_cloneSubTree_2")
set_tests_properties(dcmsr_cloneSubTree_2 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_extractSubTree "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_extractSubTree")
set_tests_properties(dcmsr_extractSubTree PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_addContentItem "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_addContentItem")
set_tests_properties(dcmsr_addContentItem PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_copyContentItem "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_copyContentItem")
set_tests_properties(dcmsr_copyContentItem PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_gotoNamedNode "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_gotoNamedNode")
set_tests_properties(dcmsr_gotoNamedNode PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_createDocSubTree "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_createDocSubTree")
set_tests_properties(dcmsr_createDocSubTree PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_copyDocSubTree "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_copyDocSubTree")
set_tests_properties(dcmsr_copyDocSubTree PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_cloneDocSubTree "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_cloneDocSubTree")
set_tests_properties(dcmsr_cloneDocSubTree PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_insertDocSubTree_1 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_insertDocSubTree_1")
set_tests_properties(dcmsr_insertDocSubTree_1 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_insertDocSubTree_2 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_insertDocSubTree_2")
set_tests_properties(dcmsr_insertDocSubTree_2 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_insertDocSubTree_3 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_insertDocSubTree_3")
set_tests_properties(dcmsr_insertDocSubTree_3 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_removeDocSubTree "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_removeDocSubTree")
set_tests_properties(dcmsr_removeDocSubTree PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_extractDocSubTree_1 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_extractDocSubTree_1")
set_tests_properties(dcmsr_extractDocSubTree_1 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_extractDocSubTree_2 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_extractDocSubTree_2")
set_tests_properties(dcmsr_extractDocSubTree_2 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_extractAndInsertDocSubTree_1 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_extractAndInsertDocSubTree_1")
set_tests_properties(dcmsr_extractAndInsertDocSubTree_1 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_extractAndInsertDocSubTree_2 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_extractAndInsertDocSubTree_2")
set_tests_properties(dcmsr_extractAndInsertDocSubTree_2 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_changeDocumentType_1 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_changeDocumentType_1")
set_tests_properties(dcmsr_changeDocumentType_1 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_changeDocumentType_2 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_changeDocumentType_2")
set_tests_properties(dcmsr_changeDocumentType_2 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_setDocumentTree "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_setDocumentTree")
set_tests_properties(dcmsr_setDocumentTree PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_rootTemplate "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_rootTemplate")
set_tests_properties(dcmsr_rootTemplate PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_subTemplate_1 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_subTemplate_1")
set_tests_properties(dcmsr_subTemplate_1 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_subTemplate_2 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_subTemplate_2")
set_tests_properties(dcmsr_subTemplate_2 PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_setCodeValueType "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_setCodeValueType")
set_tests_properties(dcmsr_setCodeValueType PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_determineCodeValueType "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_determineCodeValueType")
set_tests_properties(dcmsr_determineCodeValueType PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_writeCodeSequence "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_writeCodeSequence")
set_tests_properties(dcmsr_writeCodeSequence PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_useBasicCodedEntry "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_useBasicCodedEntry")
set_tests_properties(dcmsr_useBasicCodedEntry PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_CID42_NumericValueQualifier "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_CID42_NumericValueQualifier")
set_tests_properties(dcmsr_CID42_NumericValueQualifier PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_CID7445_DeviceParticipatingRoles "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_CID7445_DeviceParticipatingRoles")
set_tests_properties(dcmsr_CID7445_DeviceParticipatingRoles PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_TID1001_ObservationContext "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_TID1001_ObservationContext")
set_tests_properties(dcmsr_TID1001_ObservationContext PROPERTIES  LABELS "dcmsr")
add_test(dcmsr_TID1204_LanguageOfContentItemAndDescendants "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmsr_tests" "dcmsr_TID1204_LanguageOfContentItemAndDescendants")
set_tests_properties(dcmsr_TID1204_LanguageOfContentItemAndDescendants PROPERTIES  LABELS "dcmsr")
