# Generated by CMake, DO NOT EDIT
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/xcode/CMakeFiles/cmake.check_cache: \
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmdata/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmdata/apps/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmdata/data/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmdata/docs/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmdata/include/dcmtk/dcmdata/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmdata/include/dcmtk/dcmdata/libi2d/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmdata/libi2d/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmdata/libsrc/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmdata/tests/CMakeLists.txt
	/Users/seanashton/Applications/CMake.app/Contents/bin/cmake -H/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0 -B/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/xcode
