# Generated by CMake, DO NOT EDIT
/Users/seanashton/src/dcmtk-ios/xcode/CMakeFiles/cmake.check_cache: \
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmimgle/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmimgle/apps/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmimgle/data/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmimgle/include/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmimgle/libsrc/CMakeLists.txt
	/Users/seanashton/Applications/CMake.app/Contents/bin/cmake -H/Users/seanashton/src/dcmtk-ios/dcmtk -B/Users/seanashton/src/dcmtk-ios/xcode
