# Generated by CMake, DO NOT EDIT
/Users/seanashton/src/dcmtk-ios/xcode/CMakeFiles/cmake.check_cache: \
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmwlm/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmwlm/apps/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmwlm/data/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmwlm/include/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmwlm/libsrc/CMakeLists.txt
	/Users/seanashton/Applications/CMake.app/Contents/bin/cmake -H/Users/seanashton/src/dcmtk-ios/dcmtk -B/Users/seanashton/src/dcmtk-ios/xcode
