# Generated by CMake, DO NOT EDIT
/Users/seanashton/src/dcmtk-ios/xcode/CMakeFiles/cmake.check_cache: \
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmpstat/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmpstat/apps/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmpstat/data/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmpstat/etc/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmpstat/include/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmpstat/libsrc/CMakeLists.txt
	/Users/seanashton/Applications/CMake.app/Contents/bin/cmake -H/Users/seanashton/src/dcmtk-ios/dcmtk -B/Users/seanashton/src/dcmtk-ios/xcode
