# Generated by CMake, DO NOT EDIT
/Users/seanashton/src/dcmtk-ios/xcode/CMakeFiles/cmake.check_cache: \
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmsign/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmsign/apps/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmsign/include/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmsign/libsrc/CMakeLists.txt
	/Users/seanashton/Applications/CMake.app/Contents/bin/cmake -H/Users/seanashton/src/dcmtk-ios/dcmtk -B/Users/seanashton/src/dcmtk-ios/xcode
