# Generated by CMake, DO NOT EDIT
/Users/seanashton/src/dcmtk-ios/xcode/CMakeFiles/cmake.check_cache: \
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmrt/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmrt/apps/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmrt/include/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmrt/libsrc/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmrt/tests/CMakeLists.txt
	/Users/seanashton/Applications/CMake.app/Contents/bin/cmake -H/Users/seanashton/src/dcmtk-ios/dcmtk -B/Users/seanashton/src/dcmtk-ios/xcode
