# Generated by CMake, DO NOT EDIT
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/xcode/CMakeFiles/cmake.check_cache: \
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmpstat/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmpstat/apps/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmpstat/data/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmpstat/etc/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmpstat/include/dcmtk/dcmpstat/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmpstat/libsrc/CMakeLists.txt
	/Users/seanashton/Applications/CMake.app/Contents/bin/cmake -H/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0 -B/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/xcode
