# CMake generated Testfile for 
# Source directory: /Users/seanashton/src/dcmtk-ios/dcmtk/dcmdata/tests
# Build directory: /Users/seanashton/src/dcmtk-ios/xcode/dcmdata/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(dcmdata_partialElementAccess "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_partialElementAccess")
set_tests_properties(dcmdata_partialElementAccess PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_i2d_bmp "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_i2d_bmp")
set_tests_properties(dcmdata_i2d_bmp PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_checkStringValue "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_checkStringValue")
set_tests_properties(dcmdata_checkStringValue PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_determineVM "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_determineVM")
set_tests_properties(dcmdata_determineVM PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_getValueFromString "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_getValueFromString")
set_tests_properties(dcmdata_getValueFromString PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_pathAccess "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_pathAccess")
set_tests_properties(dcmdata_pathAccess PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_dateTime "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_dateTime")
set_tests_properties(dcmdata_dateTime PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_decimalString_1 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_decimalString_1")
set_tests_properties(dcmdata_decimalString_1 PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_decimalString_2 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_decimalString_2")
set_tests_properties(dcmdata_decimalString_2 PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_decimalString_3 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_decimalString_3")
set_tests_properties(dcmdata_decimalString_3 PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_decimalString_4 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_decimalString_4")
set_tests_properties(dcmdata_decimalString_4 PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_floatingPointDouble "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_floatingPointDouble")
set_tests_properties(dcmdata_floatingPointDouble PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_personName "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_personName")
set_tests_properties(dcmdata_personName PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_uniqueIdentifier_1 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_uniqueIdentifier_1")
set_tests_properties(dcmdata_uniqueIdentifier_1 PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_uniqueIdentifier_2 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_uniqueIdentifier_2")
set_tests_properties(dcmdata_uniqueIdentifier_2 PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_VRCompare "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_VRCompare")
set_tests_properties(dcmdata_VRCompare PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_AE "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_AE")
set_tests_properties(dcmdata_elementLength_EVR_AE PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_AS "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_AS")
set_tests_properties(dcmdata_elementLength_EVR_AS PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_AT "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_AT")
set_tests_properties(dcmdata_elementLength_EVR_AT PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_CS "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_CS")
set_tests_properties(dcmdata_elementLength_EVR_CS PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_DA "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_DA")
set_tests_properties(dcmdata_elementLength_EVR_DA PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_DS "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_DS")
set_tests_properties(dcmdata_elementLength_EVR_DS PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_DT "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_DT")
set_tests_properties(dcmdata_elementLength_EVR_DT PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_FD "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_FD")
set_tests_properties(dcmdata_elementLength_EVR_FD PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_FL "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_FL")
set_tests_properties(dcmdata_elementLength_EVR_FL PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_IS "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_IS")
set_tests_properties(dcmdata_elementLength_EVR_IS PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_LO "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_LO")
set_tests_properties(dcmdata_elementLength_EVR_LO PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_LT "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_LT")
set_tests_properties(dcmdata_elementLength_EVR_LT PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_OB "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_OB")
set_tests_properties(dcmdata_elementLength_EVR_OB PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_OD "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_OD")
set_tests_properties(dcmdata_elementLength_EVR_OD PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_OF "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_OF")
set_tests_properties(dcmdata_elementLength_EVR_OF PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_OW "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_OW")
set_tests_properties(dcmdata_elementLength_EVR_OW PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_OverlayData "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_OverlayData")
set_tests_properties(dcmdata_elementLength_EVR_OverlayData PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_PN "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_PN")
set_tests_properties(dcmdata_elementLength_EVR_PN PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_PixelData "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_PixelData")
set_tests_properties(dcmdata_elementLength_EVR_PixelData PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_SH "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_SH")
set_tests_properties(dcmdata_elementLength_EVR_SH PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_SL "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_SL")
set_tests_properties(dcmdata_elementLength_EVR_SL PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_SQ "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_SQ")
set_tests_properties(dcmdata_elementLength_EVR_SQ PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_SS "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_SS")
set_tests_properties(dcmdata_elementLength_EVR_SS PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_ST "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_ST")
set_tests_properties(dcmdata_elementLength_EVR_ST PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_TM "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_TM")
set_tests_properties(dcmdata_elementLength_EVR_TM PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_UC "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_UC")
set_tests_properties(dcmdata_elementLength_EVR_UC PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_UI "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_UI")
set_tests_properties(dcmdata_elementLength_EVR_UI PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_UL "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_UL")
set_tests_properties(dcmdata_elementLength_EVR_UL PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_UN "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_UN")
set_tests_properties(dcmdata_elementLength_EVR_UN PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_UNKNOWN "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_UNKNOWN")
set_tests_properties(dcmdata_elementLength_EVR_UNKNOWN PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_UNKNOWN2B "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_UNKNOWN2B")
set_tests_properties(dcmdata_elementLength_EVR_UNKNOWN2B PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_UR "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_UR")
set_tests_properties(dcmdata_elementLength_EVR_UR PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_US "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_US")
set_tests_properties(dcmdata_elementLength_EVR_US PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_UT "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_UT")
set_tests_properties(dcmdata_elementLength_EVR_UT PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_lt "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_lt")
set_tests_properties(dcmdata_elementLength_EVR_lt PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_na "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_na")
set_tests_properties(dcmdata_elementLength_EVR_na PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_ox "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_ox")
set_tests_properties(dcmdata_elementLength_EVR_ox PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_up "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_up")
set_tests_properties(dcmdata_elementLength_EVR_up PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_EVR_xs "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_EVR_xs")
set_tests_properties(dcmdata_elementLength_EVR_xs PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_pixelItem "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_pixelItem")
set_tests_properties(dcmdata_elementLength_pixelItem PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementLength_pixelSequence "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementLength_pixelSequence")
set_tests_properties(dcmdata_elementLength_pixelSequence PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_elementParent "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_elementParent")
set_tests_properties(dcmdata_elementParent PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_parser_missingDelimitationItems "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_parser_missingDelimitationItems")
set_tests_properties(dcmdata_parser_missingDelimitationItems PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_parser_missingSequenceDelimitationItem_1 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_parser_missingSequenceDelimitationItem_1")
set_tests_properties(dcmdata_parser_missingSequenceDelimitationItem_1 PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_parser_missingSequenceDelimitationItem_2 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_parser_missingSequenceDelimitationItem_2")
set_tests_properties(dcmdata_parser_missingSequenceDelimitationItem_2 PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_parser_wrongDelimitationItemForSequence "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_parser_wrongDelimitationItemForSequence")
set_tests_properties(dcmdata_parser_wrongDelimitationItemForSequence PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_parser_wrongDelimitationItemForItem "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_parser_wrongDelimitationItemForItem")
set_tests_properties(dcmdata_parser_wrongDelimitationItemForItem PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_parser_explicitItemLengthTooLarge "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_parser_explicitItemLengthTooLarge")
set_tests_properties(dcmdata_parser_explicitItemLengthTooLarge PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_parser_oddLengthPartialValue_lastItem "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_parser_oddLengthPartialValue_lastItem")
set_tests_properties(dcmdata_parser_oddLengthPartialValue_lastItem PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_parser_oddLengthPartialValue_notLastItem "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_parser_oddLengthPartialValue_notLastItem")
set_tests_properties(dcmdata_parser_oddLengthPartialValue_notLastItem PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_parser_wrongExplicitVRinDataset_default "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_parser_wrongExplicitVRinDataset_default")
set_tests_properties(dcmdata_parser_wrongExplicitVRinDataset_default PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_parser_wrongExplicitVRinDataset_defaultVR_dictLen "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_parser_wrongExplicitVRinDataset_defaultVR_dictLen")
set_tests_properties(dcmdata_parser_wrongExplicitVRinDataset_defaultVR_dictLen PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_parser_wrongExplicitVRinDataset_dictVR_defaultLen "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_parser_wrongExplicitVRinDataset_dictVR_defaultLen")
set_tests_properties(dcmdata_parser_wrongExplicitVRinDataset_dictVR_defaultLen PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_parser_wrongExplicitVRinDataset_preferDataDict "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_parser_wrongExplicitVRinDataset_preferDataDict")
set_tests_properties(dcmdata_parser_wrongExplicitVRinDataset_preferDataDict PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_parser_undefinedLengthUNSequence "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_parser_undefinedLengthUNSequence")
set_tests_properties(dcmdata_parser_undefinedLengthUNSequence PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_readingDataDictionary "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_readingDataDictionary")
set_tests_properties(dcmdata_readingDataDictionary PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_usingDataDictionary "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_usingDataDictionary")
set_tests_properties(dcmdata_usingDataDictionary PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_specificCharacterSet_1 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_specificCharacterSet_1")
set_tests_properties(dcmdata_specificCharacterSet_1 PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_specificCharacterSet_2 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_specificCharacterSet_2")
set_tests_properties(dcmdata_specificCharacterSet_2 PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_specificCharacterSet_3 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_specificCharacterSet_3")
set_tests_properties(dcmdata_specificCharacterSet_3 PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_specificCharacterSet_4 "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_specificCharacterSet_4")
set_tests_properties(dcmdata_specificCharacterSet_4 PROPERTIES  LABELS "dcmdata")
add_test(dcmdata_attribute_filter "/Users/seanashton/src/dcmtk-ios/xcode/bin/dcmdata_tests" "dcmdata_attribute_filter")
set_tests_properties(dcmdata_attribute_filter PROPERTIES  LABELS "dcmdata")
