# Generated by CMake, DO NOT EDIT
/Users/seanashton/src/dcmtk-ios/xcode/CMakeFiles/cmake.check_cache: \
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmimage/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmimage/apps/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmimage/include/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmimage/libsrc/CMakeLists.txt
	/Users/seanashton/Applications/CMake.app/Contents/bin/cmake -H/Users/seanashton/src/dcmtk-ios/dcmtk -B/Users/seanashton/src/dcmtk-ios/xcode
