# CMake generated Testfile for 
# Source directory: /Users/seanashton/src/dcmtk-ios/dcmtk/ofstd/tests
# Build directory: /Users/seanashton/src/dcmtk-ios/xcode/ofstd/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ofstd_OFCharacterEncoding_1 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFCharacterEncoding_1")
set_tests_properties(ofstd_OFCharacterEncoding_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_2 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFCharacterEncoding_2")
set_tests_properties(ofstd_OFCharacterEncoding_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_3 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFCharacterEncoding_3")
set_tests_properties(ofstd_OFCharacterEncoding_3 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_4 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFCharacterEncoding_4")
set_tests_properties(ofstd_OFCharacterEncoding_4 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_5 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFCharacterEncoding_5")
set_tests_properties(ofstd_OFCharacterEncoding_5 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_6 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFCharacterEncoding_6")
set_tests_properties(ofstd_OFCharacterEncoding_6 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_7 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFCharacterEncoding_7")
set_tests_properties(ofstd_OFCharacterEncoding_7 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_8 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFCharacterEncoding_8")
set_tests_properties(ofstd_OFCharacterEncoding_8 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFDate "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFDate")
set_tests_properties(ofstd_OFDate PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFDateTime "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFDateTime")
set_tests_properties(ofstd_OFDateTime PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFList_1 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFList_1")
set_tests_properties(ofstd_OFList_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFList_2 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFList_2")
set_tests_properties(ofstd_OFList_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFList_splice "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFList_splice")
set_tests_properties(ofstd_OFList_splice PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFMap "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFMap")
set_tests_properties(ofstd_OFMap PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFStack "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFStack")
set_tests_properties(ofstd_OFStack PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFStandard_isReadWriteable "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFStandard_isReadWriteable")
set_tests_properties(ofstd_OFStandard_isReadWriteable PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFStandard_appendFilenameExtension "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFStandard_appendFilenameExtension")
set_tests_properties(ofstd_OFStandard_appendFilenameExtension PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFStandard_removeRootDirFromPathname "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFStandard_removeRootDirFromPathname")
set_tests_properties(ofstd_OFStandard_removeRootDirFromPathname PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFFile "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFFile")
set_tests_properties(ofstd_OFFile PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_compare "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFString_compare")
set_tests_properties(ofstd_OFString_compare PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_concatenate "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFString_concatenate")
set_tests_properties(ofstd_OFString_concatenate PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_constructor "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFString_constructor")
set_tests_properties(ofstd_OFString_constructor PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_copy "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFString_copy")
set_tests_properties(ofstd_OFString_copy PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_identity_1 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFString_identity_1")
set_tests_properties(ofstd_OFString_identity_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_identity_2 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFString_identity_2")
set_tests_properties(ofstd_OFString_identity_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_identity_3 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFString_identity_3")
set_tests_properties(ofstd_OFString_identity_3 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_reserve "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFString_reserve")
set_tests_properties(ofstd_OFString_reserve PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_substr "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFString_substr")
set_tests_properties(ofstd_OFString_substr PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFTime "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFTime")
set_tests_properties(ofstd_OFTime PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFUUID_1 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFUUID_1")
set_tests_properties(ofstd_OFUUID_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFUUID_2 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFUUID_2")
set_tests_properties(ofstd_OFUUID_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFVector "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_OFVector")
set_tests_properties(ofstd_OFVector PROPERTIES  LABELS "ofstd")
add_test(ofstd_atof "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_atof")
set_tests_properties(ofstd_atof PROPERTIES  LABELS "ofstd")
add_test(ofstd_base64_1 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_base64_1")
set_tests_properties(ofstd_base64_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_base64_2 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_base64_2")
set_tests_properties(ofstd_base64_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_base64_3 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_base64_3")
set_tests_properties(ofstd_base64_3 PROPERTIES  LABELS "ofstd")
add_test(ofstd_ftoa "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_ftoa")
set_tests_properties(ofstd_ftoa PROPERTIES  LABELS "ofstd")
add_test(ofstd_markup_1 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_markup_1")
set_tests_properties(ofstd_markup_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_markup_2 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_markup_2")
set_tests_properties(ofstd_markup_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_markup_3 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_markup_3")
set_tests_properties(ofstd_markup_3 PROPERTIES  LABELS "ofstd")
add_test(ofstd_markup_4 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_markup_4")
set_tests_properties(ofstd_markup_4 PROPERTIES  LABELS "ofstd")
add_test(ofstd_markup_5 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_markup_5")
set_tests_properties(ofstd_markup_5 PROPERTIES  LABELS "ofstd")
add_test(ofstd_markup_6 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_markup_6")
set_tests_properties(ofstd_markup_6 PROPERTIES  LABELS "ofstd")
add_test(ofstd_testPaths_1 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_testPaths_1")
set_tests_properties(ofstd_testPaths_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_testPaths_2 "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_testPaths_2")
set_tests_properties(ofstd_testPaths_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_thread "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_thread")
set_tests_properties(ofstd_thread PROPERTIES  LABELS "ofstd")
add_test(ofstd_xmlParser "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_xmlParser")
set_tests_properties(ofstd_xmlParser PROPERTIES  LABELS "ofstd")
add_test(ofstd_memory "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_memory")
set_tests_properties(ofstd_memory PROPERTIES  LABELS "ofstd")
add_test(ofstd_optional "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_optional")
set_tests_properties(ofstd_optional PROPERTIES  LABELS "ofstd")
add_test(ofstd_tuple "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_tuple")
set_tests_properties(ofstd_tuple PROPERTIES  LABELS "ofstd")
add_test(ofstd_limits "/Users/seanashton/src/dcmtk-ios/xcode/bin/ofstd_tests" "ofstd_limits")
set_tests_properties(ofstd_limits PROPERTIES  LABELS "ofstd")
