# Generated by CMake, DO NOT EDIT
/Users/seanashton/src/dcmtk-ios/xcode/CMakeFiles/cmake.check_cache: \
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmqrdb/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmqrdb/apps/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmqrdb/docs/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmqrdb/etc/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmqrdb/include/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmqrdb/libsrc/CMakeLists.txt
	/Users/seanashton/Applications/CMake.app/Contents/bin/cmake -H/Users/seanashton/src/dcmtk-ios/dcmtk -B/Users/seanashton/src/dcmtk-ios/xcode
