# Generated by CMake, DO NOT EDIT
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/xcode/CMakeFiles/cmake.check_cache: \
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/oflog/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/oflog/etc/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/oflog/include/dcmtk/oflog/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/oflog/include/dcmtk/oflog/config/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/oflog/include/dcmtk/oflog/helpers/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/oflog/include/dcmtk/oflog/spi/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/oflog/libsrc/CMakeLists.txt
	/Users/seanashton/Applications/CMake.app/Contents/bin/cmake -H/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0 -B/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/xcode
