# Generated by CMake, DO NOT EDIT
/Users/seanashton/src/dcmtk-ios/xcode/CMakeFiles/cmake.check_cache: \
/Users/seanashton/src/dcmtk-ios/dcmtk/oflog/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/oflog/etc/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/oflog/include/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/oflog/libsrc/CMakeLists.txt
	/Users/seanashton/Applications/CMake.app/Contents/bin/cmake -H/Users/seanashton/src/dcmtk-ios/dcmtk -B/Users/seanashton/src/dcmtk-ios/xcode
