# Generated by CMake, DO NOT EDIT
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/xcode/CMakeFiles/cmake.check_cache: \
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmjpeg/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmjpeg/apps/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmjpeg/include/dcmtk/dcmjpeg/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmjpeg/libijg12/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmjpeg/libijg16/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmjpeg/libijg8/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmjpeg/libsrc/CMakeLists.txt
	/Users/seanashton/Applications/CMake.app/Contents/bin/cmake -H/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0 -B/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/xcode
