# Generated by CMake, DO NOT EDIT
/Users/seanashton/src/dcmtk-ios/xcode/CMakeFiles/cmake.check_cache: \
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmdata/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmdata/apps/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmdata/data/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmdata/docs/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmdata/include/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmdata/libi2d/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmdata/libsrc/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmdata/tests/CMakeLists.txt
	/Users/seanashton/Applications/CMake.app/Contents/bin/cmake -H/Users/seanashton/src/dcmtk-ios/dcmtk -B/Users/seanashton/src/dcmtk-ios/xcode
