# Generated by CMake, DO NOT EDIT
/Users/seanashton/src/dcmtk-ios/xcode/CMakeFiles/cmake.check_cache: \
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmjpls/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmjpls/apps/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmjpls/include/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmjpls/libcharls/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmjpls/libsrc/CMakeLists.txt
	/Users/seanashton/Applications/CMake.app/Contents/bin/cmake -H/Users/seanashton/src/dcmtk-ios/dcmtk -B/Users/seanashton/src/dcmtk-ios/xcode
