# Generated by CMake, DO NOT EDIT
/Users/seanashton/src/dcmtk-ios/xcode/CMakeFiles/cmake.check_cache: \
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmsr/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmsr/apps/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmsr/data/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmsr/include/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmsr/libcmr/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmsr/libsrc/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmsr/tests/CMakeLists.txt
	/Users/seanashton/Applications/CMake.app/Contents/bin/cmake -H/Users/seanashton/src/dcmtk-ios/dcmtk -B/Users/seanashton/src/dcmtk-ios/xcode
