# Generated by CMake 3.2.3

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget ofstd oflog dcmdata i2d dcmimgle dcmimage dcmjpeg ijg8 ijg12 ijg16 dcmjpls charls dcmtls dcmnet dcmsr cmr dcmdsig dcmwlm dcmqrdb dcmpstat dcmrt)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target ofstd
add_library(ofstd STATIC IMPORTED)

# Create imported target oflog
add_library(oflog STATIC IMPORTED)

# Create imported target dcmdata
add_library(dcmdata STATIC IMPORTED)

# Create imported target i2d
add_library(i2d STATIC IMPORTED)

# Create imported target dcmimgle
add_library(dcmimgle STATIC IMPORTED)

# Create imported target dcmimage
add_library(dcmimage STATIC IMPORTED)

# Create imported target dcmjpeg
add_library(dcmjpeg STATIC IMPORTED)

# Create imported target ijg8
add_library(ijg8 STATIC IMPORTED)

# Create imported target ijg12
add_library(ijg12 STATIC IMPORTED)

# Create imported target ijg16
add_library(ijg16 STATIC IMPORTED)

# Create imported target dcmjpls
add_library(dcmjpls STATIC IMPORTED)

# Create imported target charls
add_library(charls STATIC IMPORTED)

# Create imported target dcmtls
add_library(dcmtls STATIC IMPORTED)

# Create imported target dcmnet
add_library(dcmnet STATIC IMPORTED)

# Create imported target dcmsr
add_library(dcmsr STATIC IMPORTED)

# Create imported target cmr
add_library(cmr STATIC IMPORTED)

# Create imported target dcmdsig
add_library(dcmdsig STATIC IMPORTED)

# Create imported target dcmwlm
add_library(dcmwlm STATIC IMPORTED)

# Create imported target dcmqrdb
add_library(dcmqrdb STATIC IMPORTED)

# Create imported target dcmpstat
add_library(dcmpstat STATIC IMPORTED)

# Create imported target dcmrt
add_library(dcmrt STATIC IMPORTED)

# Import target "ofstd" for configuration "Debug"
set_property(TARGET ofstd APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ofstd PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libofstd.a"
  )

# Import target "oflog" for configuration "Debug"
set_property(TARGET oflog APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(oflog PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "ofstd"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/liboflog.a"
  )

# Import target "dcmdata" for configuration "Debug"
set_property(TARGET dcmdata APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(dcmdata PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "ofstd;oflog;/usr/lib/libz.dylib"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libdcmdata.a"
  )

# Import target "i2d" for configuration "Debug"
set_property(TARGET i2d APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(i2d PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "dcmdata"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libi2d.a"
  )

# Import target "dcmimgle" for configuration "Debug"
set_property(TARGET dcmimgle APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(dcmimgle PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "ofstd;oflog;dcmdata"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libdcmimgle.a"
  )

# Import target "dcmimage" for configuration "Debug"
set_property(TARGET dcmimage APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(dcmimage PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "oflog;dcmdata;dcmimgle"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libdcmimage.a"
  )

# Import target "dcmjpeg" for configuration "Debug"
set_property(TARGET dcmjpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(dcmjpeg PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "ofstd;oflog;dcmdata;dcmimgle;dcmimage;ijg8;ijg12;ijg16"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libdcmjpeg.a"
  )

# Import target "ijg8" for configuration "Debug"
set_property(TARGET ijg8 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ijg8 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libijg8.a"
  )

# Import target "ijg12" for configuration "Debug"
set_property(TARGET ijg12 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ijg12 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libijg12.a"
  )

# Import target "ijg16" for configuration "Debug"
set_property(TARGET ijg16 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ijg16 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libijg16.a"
  )

# Import target "dcmjpls" for configuration "Debug"
set_property(TARGET dcmjpls APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(dcmjpls PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "ofstd;oflog;dcmdata;dcmimgle;dcmimage;charls"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libdcmjpls.a"
  )

# Import target "charls" for configuration "Debug"
set_property(TARGET charls APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(charls PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libcharls.a"
  )

# Import target "dcmtls" for configuration "Debug"
set_property(TARGET dcmtls APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(dcmtls PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "ofstd;dcmdata;dcmnet"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libdcmtls.a"
  )

# Import target "dcmnet" for configuration "Debug"
set_property(TARGET dcmnet APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(dcmnet PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "ofstd;oflog;dcmdata"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libdcmnet.a"
  )

# Import target "dcmsr" for configuration "Debug"
set_property(TARGET dcmsr APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(dcmsr PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "ofstd;oflog;dcmdata;dcmimgle;dcmimage"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libdcmsr.a"
  )

# Import target "cmr" for configuration "Debug"
set_property(TARGET cmr APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(cmr PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "dcmsr"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libcmr.a"
  )

# Import target "dcmdsig" for configuration "Debug"
set_property(TARGET dcmdsig APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(dcmdsig PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "ofstd;dcmdata"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libdcmdsig.a"
  )

# Import target "dcmwlm" for configuration "Debug"
set_property(TARGET dcmwlm APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(dcmwlm PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "ofstd;dcmdata;dcmnet"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libdcmwlm.a"
  )

# Import target "dcmqrdb" for configuration "Debug"
set_property(TARGET dcmqrdb APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(dcmqrdb PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "ofstd;dcmdata;dcmnet"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libdcmqrdb.a"
  )

# Import target "dcmpstat" for configuration "Debug"
set_property(TARGET dcmpstat APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(dcmpstat PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "ofstd;oflog;dcmdata;dcmimgle;dcmimage;dcmnet;dcmdsig;dcmtls;dcmsr;dcmqrdb"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libdcmpstat.a"
  )

# Import target "dcmrt" for configuration "Debug"
set_property(TARGET dcmrt APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(dcmrt PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "ofstd;oflog;dcmdata;dcmimgle"
  IMPORTED_LOCATION_DEBUG "/Users/seanashton/src/dcmtk-ios/xcode/lib/Debug/libdcmrt.a"
  )

# Import target "ofstd" for configuration "Release"
set_property(TARGET ofstd APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ofstd PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libofstd.a"
  )

# Import target "oflog" for configuration "Release"
set_property(TARGET oflog APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(oflog PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/liboflog.a"
  )

# Import target "dcmdata" for configuration "Release"
set_property(TARGET dcmdata APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmdata PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;oflog;/usr/lib/libz.dylib"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libdcmdata.a"
  )

# Import target "i2d" for configuration "Release"
set_property(TARGET i2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(i2d PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "dcmdata"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libi2d.a"
  )

# Import target "dcmimgle" for configuration "Release"
set_property(TARGET dcmimgle APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmimgle PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;oflog;dcmdata"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libdcmimgle.a"
  )

# Import target "dcmimage" for configuration "Release"
set_property(TARGET dcmimage APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmimage PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "oflog;dcmdata;dcmimgle"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libdcmimage.a"
  )

# Import target "dcmjpeg" for configuration "Release"
set_property(TARGET dcmjpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmjpeg PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;oflog;dcmdata;dcmimgle;dcmimage;ijg8;ijg12;ijg16"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libdcmjpeg.a"
  )

# Import target "ijg8" for configuration "Release"
set_property(TARGET ijg8 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ijg8 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libijg8.a"
  )

# Import target "ijg12" for configuration "Release"
set_property(TARGET ijg12 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ijg12 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libijg12.a"
  )

# Import target "ijg16" for configuration "Release"
set_property(TARGET ijg16 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ijg16 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libijg16.a"
  )

# Import target "dcmjpls" for configuration "Release"
set_property(TARGET dcmjpls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmjpls PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;oflog;dcmdata;dcmimgle;dcmimage;charls"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libdcmjpls.a"
  )

# Import target "charls" for configuration "Release"
set_property(TARGET charls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(charls PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libcharls.a"
  )

# Import target "dcmtls" for configuration "Release"
set_property(TARGET dcmtls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmtls PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;dcmdata;dcmnet"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libdcmtls.a"
  )

# Import target "dcmnet" for configuration "Release"
set_property(TARGET dcmnet APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmnet PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;oflog;dcmdata"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libdcmnet.a"
  )

# Import target "dcmsr" for configuration "Release"
set_property(TARGET dcmsr APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmsr PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;oflog;dcmdata;dcmimgle;dcmimage"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libdcmsr.a"
  )

# Import target "cmr" for configuration "Release"
set_property(TARGET cmr APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(cmr PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "dcmsr"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libcmr.a"
  )

# Import target "dcmdsig" for configuration "Release"
set_property(TARGET dcmdsig APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmdsig PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;dcmdata"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libdcmdsig.a"
  )

# Import target "dcmwlm" for configuration "Release"
set_property(TARGET dcmwlm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmwlm PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;dcmdata;dcmnet"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libdcmwlm.a"
  )

# Import target "dcmqrdb" for configuration "Release"
set_property(TARGET dcmqrdb APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmqrdb PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;dcmdata;dcmnet"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libdcmqrdb.a"
  )

# Import target "dcmpstat" for configuration "Release"
set_property(TARGET dcmpstat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmpstat PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;oflog;dcmdata;dcmimgle;dcmimage;dcmnet;dcmdsig;dcmtls;dcmsr;dcmqrdb"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libdcmpstat.a"
  )

# Import target "dcmrt" for configuration "Release"
set_property(TARGET dcmrt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmrt PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;oflog;dcmdata;dcmimgle"
  IMPORTED_LOCATION_RELEASE "/Users/seanashton/src/dcmtk-ios/xcode/lib/Release/libdcmrt.a"
  )

# Import target "ofstd" for configuration "MinSizeRel"
set_property(TARGET ofstd APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(ofstd PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libofstd.a"
  )

# Import target "oflog" for configuration "MinSizeRel"
set_property(TARGET oflog APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(oflog PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "ofstd"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/liboflog.a"
  )

# Import target "dcmdata" for configuration "MinSizeRel"
set_property(TARGET dcmdata APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(dcmdata PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "ofstd;oflog;/usr/lib/libz.dylib"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libdcmdata.a"
  )

# Import target "i2d" for configuration "MinSizeRel"
set_property(TARGET i2d APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(i2d PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "dcmdata"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libi2d.a"
  )

# Import target "dcmimgle" for configuration "MinSizeRel"
set_property(TARGET dcmimgle APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(dcmimgle PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "ofstd;oflog;dcmdata"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libdcmimgle.a"
  )

# Import target "dcmimage" for configuration "MinSizeRel"
set_property(TARGET dcmimage APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(dcmimage PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "oflog;dcmdata;dcmimgle"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libdcmimage.a"
  )

# Import target "dcmjpeg" for configuration "MinSizeRel"
set_property(TARGET dcmjpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(dcmjpeg PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "ofstd;oflog;dcmdata;dcmimgle;dcmimage;ijg8;ijg12;ijg16"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libdcmjpeg.a"
  )

# Import target "ijg8" for configuration "MinSizeRel"
set_property(TARGET ijg8 APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(ijg8 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libijg8.a"
  )

# Import target "ijg12" for configuration "MinSizeRel"
set_property(TARGET ijg12 APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(ijg12 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libijg12.a"
  )

# Import target "ijg16" for configuration "MinSizeRel"
set_property(TARGET ijg16 APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(ijg16 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libijg16.a"
  )

# Import target "dcmjpls" for configuration "MinSizeRel"
set_property(TARGET dcmjpls APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(dcmjpls PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "ofstd;oflog;dcmdata;dcmimgle;dcmimage;charls"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libdcmjpls.a"
  )

# Import target "charls" for configuration "MinSizeRel"
set_property(TARGET charls APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(charls PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libcharls.a"
  )

# Import target "dcmtls" for configuration "MinSizeRel"
set_property(TARGET dcmtls APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(dcmtls PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "ofstd;dcmdata;dcmnet"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libdcmtls.a"
  )

# Import target "dcmnet" for configuration "MinSizeRel"
set_property(TARGET dcmnet APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(dcmnet PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "ofstd;oflog;dcmdata"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libdcmnet.a"
  )

# Import target "dcmsr" for configuration "MinSizeRel"
set_property(TARGET dcmsr APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(dcmsr PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "ofstd;oflog;dcmdata;dcmimgle;dcmimage"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libdcmsr.a"
  )

# Import target "cmr" for configuration "MinSizeRel"
set_property(TARGET cmr APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(cmr PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "dcmsr"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libcmr.a"
  )

# Import target "dcmdsig" for configuration "MinSizeRel"
set_property(TARGET dcmdsig APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(dcmdsig PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "ofstd;dcmdata"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libdcmdsig.a"
  )

# Import target "dcmwlm" for configuration "MinSizeRel"
set_property(TARGET dcmwlm APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(dcmwlm PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "ofstd;dcmdata;dcmnet"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libdcmwlm.a"
  )

# Import target "dcmqrdb" for configuration "MinSizeRel"
set_property(TARGET dcmqrdb APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(dcmqrdb PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "ofstd;dcmdata;dcmnet"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libdcmqrdb.a"
  )

# Import target "dcmpstat" for configuration "MinSizeRel"
set_property(TARGET dcmpstat APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(dcmpstat PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "ofstd;oflog;dcmdata;dcmimgle;dcmimage;dcmnet;dcmdsig;dcmtls;dcmsr;dcmqrdb"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libdcmpstat.a"
  )

# Import target "dcmrt" for configuration "MinSizeRel"
set_property(TARGET dcmrt APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(dcmrt PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "ofstd;oflog;dcmdata;dcmimgle"
  IMPORTED_LOCATION_MINSIZEREL "/Users/seanashton/src/dcmtk-ios/xcode/lib/MinSizeRel/libdcmrt.a"
  )

# Import target "ofstd" for configuration "RelWithDebInfo"
set_property(TARGET ofstd APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(ofstd PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libofstd.a"
  )

# Import target "oflog" for configuration "RelWithDebInfo"
set_property(TARGET oflog APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(oflog PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "ofstd"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/liboflog.a"
  )

# Import target "dcmdata" for configuration "RelWithDebInfo"
set_property(TARGET dcmdata APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(dcmdata PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "ofstd;oflog;/usr/lib/libz.dylib"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libdcmdata.a"
  )

# Import target "i2d" for configuration "RelWithDebInfo"
set_property(TARGET i2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(i2d PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "dcmdata"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libi2d.a"
  )

# Import target "dcmimgle" for configuration "RelWithDebInfo"
set_property(TARGET dcmimgle APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(dcmimgle PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "ofstd;oflog;dcmdata"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libdcmimgle.a"
  )

# Import target "dcmimage" for configuration "RelWithDebInfo"
set_property(TARGET dcmimage APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(dcmimage PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "oflog;dcmdata;dcmimgle"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libdcmimage.a"
  )

# Import target "dcmjpeg" for configuration "RelWithDebInfo"
set_property(TARGET dcmjpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(dcmjpeg PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "ofstd;oflog;dcmdata;dcmimgle;dcmimage;ijg8;ijg12;ijg16"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libdcmjpeg.a"
  )

# Import target "ijg8" for configuration "RelWithDebInfo"
set_property(TARGET ijg8 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(ijg8 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libijg8.a"
  )

# Import target "ijg12" for configuration "RelWithDebInfo"
set_property(TARGET ijg12 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(ijg12 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libijg12.a"
  )

# Import target "ijg16" for configuration "RelWithDebInfo"
set_property(TARGET ijg16 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(ijg16 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libijg16.a"
  )

# Import target "dcmjpls" for configuration "RelWithDebInfo"
set_property(TARGET dcmjpls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(dcmjpls PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "ofstd;oflog;dcmdata;dcmimgle;dcmimage;charls"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libdcmjpls.a"
  )

# Import target "charls" for configuration "RelWithDebInfo"
set_property(TARGET charls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(charls PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libcharls.a"
  )

# Import target "dcmtls" for configuration "RelWithDebInfo"
set_property(TARGET dcmtls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(dcmtls PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "ofstd;dcmdata;dcmnet"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libdcmtls.a"
  )

# Import target "dcmnet" for configuration "RelWithDebInfo"
set_property(TARGET dcmnet APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(dcmnet PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "ofstd;oflog;dcmdata"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libdcmnet.a"
  )

# Import target "dcmsr" for configuration "RelWithDebInfo"
set_property(TARGET dcmsr APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(dcmsr PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "ofstd;oflog;dcmdata;dcmimgle;dcmimage"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libdcmsr.a"
  )

# Import target "cmr" for configuration "RelWithDebInfo"
set_property(TARGET cmr APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(cmr PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "dcmsr"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libcmr.a"
  )

# Import target "dcmdsig" for configuration "RelWithDebInfo"
set_property(TARGET dcmdsig APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(dcmdsig PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "ofstd;dcmdata"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libdcmdsig.a"
  )

# Import target "dcmwlm" for configuration "RelWithDebInfo"
set_property(TARGET dcmwlm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(dcmwlm PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "ofstd;dcmdata;dcmnet"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libdcmwlm.a"
  )

# Import target "dcmqrdb" for configuration "RelWithDebInfo"
set_property(TARGET dcmqrdb APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(dcmqrdb PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "ofstd;dcmdata;dcmnet"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libdcmqrdb.a"
  )

# Import target "dcmpstat" for configuration "RelWithDebInfo"
set_property(TARGET dcmpstat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(dcmpstat PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "ofstd;oflog;dcmdata;dcmimgle;dcmimage;dcmnet;dcmdsig;dcmtls;dcmsr;dcmqrdb"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libdcmpstat.a"
  )

# Import target "dcmrt" for configuration "RelWithDebInfo"
set_property(TARGET dcmrt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(dcmrt PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "ofstd;oflog;dcmdata;dcmimgle"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/seanashton/src/dcmtk-ios/xcode/lib/RelWithDebInfo/libdcmrt.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
