# Generated by CMake, DO NOT EDIT
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/xcode/CMakeFiles/cmake.check_cache: \
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmwlm/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmwlm/apps/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmwlm/data/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmwlm/docs/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmwlm/include/dcmtk/dcmwlm/CMakeLists.txt\
/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/dcmwlm/libsrc/CMakeLists.txt
	/Users/seanashton/Applications/CMake.app/Contents/bin/cmake -H/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0 -B/Users/seanashton/Documents/Developer/iOS/dcmtk-3.6.0/xcode
