# Generated by CMake, DO NOT EDIT
/Users/seanashton/src/dcmtk-ios/xcode/CMakeFiles/cmake.check_cache: \
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmjpeg/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmjpeg/apps/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmjpeg/include/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmjpeg/libijg12/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmjpeg/libijg16/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmjpeg/libijg8/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmjpeg/libsrc/CMakeLists.txt
	/Users/seanashton/Applications/CMake.app/Contents/bin/cmake -H/Users/seanashton/src/dcmtk-ios/dcmtk -B/Users/seanashton/src/dcmtk-ios/xcode
