# Generated by CMake, DO NOT EDIT
/Users/seanashton/src/dcmtk-ios/xcode/CMakeFiles/cmake.check_cache: \
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmnet/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmnet/apps/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmnet/docs/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmnet/etc/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmnet/include/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmnet/libsrc/CMakeLists.txt\
/Users/seanashton/src/dcmtk-ios/dcmtk/dcmnet/tests/CMakeLists.txt
	/Users/seanashton/Applications/CMake.app/Contents/bin/cmake -H/Users/seanashton/src/dcmtk-ios/dcmtk -B/Users/seanashton/src/dcmtk-ios/xcode
